name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:
    inputs:
      YOUR_VARIABLE:
        description: 'Provide a value for YOUR_VARIABLE'
        required: true
        default: 'default_value'  # Optional default value

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set the variable (make sure YOUR_VARIABLE is passed as input)
      - name: Set YOUR_VARIABLE
        run: |
          export YOUR_VARIABLE="${{ github.event.inputs.YOUR_VARIABLE }}"
          echo "YOUR_VARIABLE is set to $YOUR_VARIABLE"
      
      # Check if the variable is set before splitting
      - name: Check input before split
        run: |
          if [ -z "$YOUR_VARIABLE" ]; then
            echo "Error: Variable is undefined"
            exit 1
          fi
          # Split the variable (if needed)
          split_result=$(echo "$YOUR_VARIABLE" | cut -d' ' -f1)
          echo "Split result: $split_result"
      
      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: gyan007
          outputs: dist/snake.svg

      # Prepare output folder
      - name: Prepare output folder
        run: mkdir -p dist

      # Move the generated SVG to the output folder
      - name: Move SVG
        run: mv snake.svg dist/snake.svg

      # Push the result to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
